In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

Kerala_floods = pd.read_csv('C:/Users/User/warnings_actual_predicted.csv')

Kerala_floods.actual_rainfall = Kerala_floods.actual_rainfall.astype('category')
Kerala_floods.actual_rainfall = Kerala_floods.actual_rainfall.cat.reorder_categories(['Green','Yellow','Orange','Red'])
Kerala_floods.actual_rainfall = Kerala_floods.actual_rainfall.cat.codes

Kerala_floods.predicted_rainfall = Kerala_floods.predicted_rainfall.astype('category')
Kerala_floods.predicted_rainfall = Kerala_floods.predicted_rainfall.cat.reorder_categories(['Green','Yellow','Orange','Red'])
Kerala_floods.predicted_rainfall = Kerala_floods.predicted_rainfall.cat.codes
X = Kerala_floods.iloc[:,2].values

y = Kerala_floods.iloc[:,3].values

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)
X_train = X_train.reshape(-1,1)
X_test = X_test.reshape(-1,1)

from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

from sklearn.linear_model import LogisticRegression
from sklearn import metrics

logreg = LogisticRegression(random_state=0)
logreg.fit(X_train, y_train)

y_pred = logreg.predict(X_test)
y_pred

from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

[[12  0  0  0]
 [ 5  7  0  8]
 [ 2  5  0  3]
 [ 4  4  0  3]]
              precision    recall  f1-score   support

           0       0.52      1.00      0.69        12
           1       0.44      0.35      0.39        20
           2       0.00      0.00      0.00        10
           3       0.21      0.27      0.24        11

    accuracy                           0.42        53
   macro avg       0.29      0.41      0.33        53
weighted avg       0.33      0.42      0.35        53



C:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
